<Project>

  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <NuGetAuditMode>all</NuGetAuditMode>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Roslyn Test Tools</Title>
    <Product>Roslyn static code analyzers test tools</Product>
    <ProductName>Roslyn Test Tools</ProductName>
    <Description>
      Tooling to describe expected static code analyzer behavior in annotated code files.
    </Description>
    <Authors>Corniel Nobel</Authors>
    <Owners>Corniel Nobel</Owners>
    <PackageTags>
      Roslyn;
      Test Tools;
      Static Code;
      Analyzers
    </PackageTags>
    <Company>Corniel Nobel</Company>
    <Copyright>Copyright © Corniel Nobel 2013-current</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ContinuousIntegrationBuild)' == 'true'">
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

</Project>
