name: Build & Test

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.x'
    - name: Build with dotnet
      run: dotnet build roslyn-test-tools.sln --configuration Release
    - name: Run unit tests
      run: dotnet test roslyn-test-tools.sln --no-build --configuration Release
